### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by liangcevv** [Osilly/Tampered-Image-Detection#1]
大佬，我是研究图像篡改检测（定位）的，能加你请教交流一下吗

**Comment by Osilly** [comment]
你好，我参加这个比赛只是因为它与语义分割相关，并未深入研究图像篡改检测（定位）领域，也只完成了baseline并未优化。建议与相关领域的研究者进行交流，我可能无法提供切实有效的回答。比赛链接为：https://tianchi.aliyun.com/competition/entrance/531945/introduction
